*===============================================================================
* 01_clean.do —— Data cleaning (raw -> analysis sample)
*
* Principle: raw data is read-only and never modified; every sample filter,
*   variable construction, and winsorization step is recorded in code so it is
*   traceable. Final output: data/clean/analysis.dta.
*===============================================================================

*--- 1. Read in raw data and merge -------------------------------------------
use "$raw/main.dta", clear                      // Main table
merge m:1 id year using "$raw/extra1.dta", keep(master match) nogen
merge m:1 area year using "$raw/extra2.dta", keep(master match) nogen
* Always state the merge keys explicitly (here id x year / area x year); record the match rate of each merge

*--- 2. Sample filters (record each step for the "Data" section) -------------
drop if category == "excluded_group"            // Drop ineligible category
drop if regexm(name, "FLAG")                     // Drop flagged units
drop if mi(Y) | mi(treat)                        // Drop missing on key variables
* Forms an unbalanced / balanced panel; for a balanced panel: bys id: keep if _N == n_periods

*--- 3. Variable construction (give formula + source notes) -------------------
gen     size = ln(asset)                         // Size = ln(total assets)
gen     lev  = debt / asset                      // Leverage ratio
gen     roa  = ni / asset                         // Return on assets
label var size "Size (log assets)"
label var lev  "Leverage ratio"
label var roa  "Return on assets"

* Treatment variable: first treated period gvar (required for staggered DID)
bys id (year): egen _first = min(cond(treat==1, year, .))
gen gvar = cond(mi(_first), 0, _first)           // Never-treated units: gvar = 0
drop _first

*--- 4. Winsorize to mitigate outliers; the cut share is tested in robustness -
winsor2 Y size lev roa, cuts(1 99) replace

*--- 5. Save the analysis sample ---------------------------------------------
compress
label data "Analysis sample, generated by 01_clean.do, do not edit by hand"
save "$clean/analysis.dta", replace
di as result "===== 01_clean.do done, N = " _N " ====="
