#!/usr/bin/env python3
"""Audit how recently each pack's volatile facts were verified against official sources.

The repository's central claim is that every pack is grounded in primary sources. That
claim decays: editors rotate, fees change, page caps move, data policies tighten. The
existing CI checks whether external *links* resolve, which is a much weaker property
than whether the *facts* were re-read recently.

This makes the claim auditable. It reads each pack's
``resources/official-source-map.md`` and derives ``last_verified`` from the dates the
document itself states.

**Nothing is stamped into the files.** The journal-selection layer's design rule is one
source of truth per fact; writing a ``last_verified`` marker next to prose that already
carries the date would be a second copy free to drift. The date is parsed instead:

1. preferred — an ISO date within a verification phrase ("access date: 2026-06-07",
   "re-verified 2026-06-22", "checked on …");
2. fallback — the newest ISO date anywhere in the file, reported as ``inferred`` so a
   reader knows it was not an explicit verification claim.

Outputs ``.maintenance/FRESHNESS.md``. That file holds only **stable** data (the dates
themselves, never an age in days) so it can be byte-checked in CI; ages are computed
against the current date at audit time.

Usage:
    python3 tools/freshness_audit.py --write
    python3 tools/freshness_audit.py --check                 # dashboard up to date?
    python3 tools/freshness_audit.py --max-age-days 240      # freshness gate
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from collections import Counter

from venue_lib import ROOT, is_depth_pack, read

OUT = ROOT / ".maintenance" / "FRESHNESS.md"

ISO = re.compile(r"\b(20[0-9]{2}-[0-9]{2}-[0-9]{2})\b")
VERIFY_CONTEXT = re.compile(
    r"(access(?:ed)?\s*date|accessed|re-?verified|verified|live[-\s]?check(?:ed)?|checked)"
    r"[^\n]{0,60}?\b(20[0-9]{2}-[0-9]{2}-[0-9]{2})\b",
    re.I,
)


def parse_date(value: str) -> dt.date | None:
    try:
        return dt.date.fromisoformat(value)
    except ValueError:
        return None


def last_verified(text: str, today: dt.date) -> tuple[dt.date | None, str]:
    """(date, provenance) where provenance is 'stated' | 'inferred' | 'none'."""
    stated = [parse_date(m.group(2)) for m in VERIFY_CONTEXT.finditer(text)]
    stated = [d for d in stated if d and d <= today]
    if stated:
        return max(stated), "stated"
    loose = [parse_date(d) for d in ISO.findall(text)]
    loose = [d for d in loose if d and d <= today]
    if loose:
        return max(loose), "inferred"
    return None, "none"


def collect(today: dt.date) -> list[dict]:
    records: list[dict] = []
    for plugin in sorted(ROOT.glob("*/.claude-plugin/plugin.json")):
        pack = plugin.parent.parent
        source_map = pack / "resources" / "official-source-map.md"
        if not source_map.exists():
            continue
        kind = "depth" if is_depth_pack(pack) else "bundle"
        date, provenance = last_verified(read(source_map), today)
        records.append({
            "pack": pack.name,
            "kind": kind,
            "last_verified": date.isoformat() if date else "",
            "provenance": provenance,
            "_date": date,
        })
    records.sort(key=lambda r: (r["_date"] or dt.date.min, r["pack"]))
    return records


def render(records: list[dict]) -> str:
    counts = Counter(r["last_verified"][:7] or "unknown" for r in records)
    provenance = Counter(r["provenance"] for r in records)
    lines = [
        "# Source-map freshness",
        "",
        "> Generated by `python3 tools/freshness_audit.py --write`. Do not edit by hand.",
        "",
        "`last_verified` is **parsed from each source map's own prose**, not stored "
        "separately — one source of truth per fact. To move a pack up this list, "
        "re-check its official pages and record the new access date in "
        "`resources/official-source-map.md`.",
        "",
        f"**{len(records)} packs with a source map.** Oldest first.",
        "",
        "| Verified | Packs |",
        "|---|---:|",
    ]
    for month, count in sorted(counts.items()):
        lines.append(f"| {month} | {count} |")
    lines += [
        "",
        f"Provenance: {provenance.get('stated', 0)} stated explicitly, "
        f"{provenance.get('inferred', 0)} inferred from the newest date in the file, "
        f"{provenance.get('none', 0)} with no date at all.",
        "",
        "## Per pack",
        "",
        "| Pack | Kind | Last verified | Provenance |",
        "|---|---|---|---|",
    ]
    for record in records:
        lines.append(
            f"| {record['pack']} | {record['kind']} | "
            f"{record['last_verified'] or '—'} | {record['provenance']} |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="write the dashboard")
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed dashboard is stale")
    parser.add_argument("--max-age-days", type=int, default=None,
                        help="fail if any pack was verified longer ago than this")
    parser.add_argument("--max-unknown", type=int, default=None,
                        help="fail if more than N packs have no verification date")
    parser.add_argument("--today", default=None,
                        help="override today's date (YYYY-MM-DD) for reproducible runs")
    args = parser.parse_args(argv)

    today = parse_date(args.today) if args.today else dt.date.today()
    if today is None:
        print(f"FAIL: --today must be YYYY-MM-DD, got {args.today!r}", file=sys.stderr)
        return 1

    records = collect(today)
    text = render(records)

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"FAIL: {OUT.relative_to(ROOT)} is stale — run "
                  "`python3 tools/freshness_audit.py --write`", file=sys.stderr)
            return 1
        print(f"OK: freshness dashboard current ({len(records)} packs)")

    if args.write:
        OUT.write_text(text, encoding="utf-8")
        print(f"wrote {OUT.relative_to(ROOT)} ({len(records)} packs)")

    dated = [r for r in records if r["_date"]]
    unknown = [r for r in records if not r["_date"]]
    if dated:
        oldest = dated[0]
        age = (today - oldest["_date"]).days
        median = (today - dated[len(dated) // 2]["_date"]).days
        print(f"as of {today}: median age {median}d, oldest {age}d "
              f"({oldest['pack']}, {oldest['last_verified']}), "
              f"{len(unknown)} without a date")

    failures = 0
    if args.max_age_days is not None:
        overdue = [r for r in dated if (today - r["_date"]).days > args.max_age_days]
        if overdue:
            failures += 1
            print(f"FAIL: {len(overdue)} pack(s) not verified in "
                  f"{args.max_age_days} days:", file=sys.stderr)
            for record in overdue[:15]:
                print(f"  {record['pack']} — {record['last_verified']}", file=sys.stderr)
    if args.max_unknown is not None and len(unknown) > args.max_unknown:
        failures += 1
        print(f"FAIL: {len(unknown)} packs have no verification date "
              f"(limit {args.max_unknown}): "
              f"{', '.join(r['pack'] for r in unknown)}", file=sys.stderr)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
