#!/usr/bin/env python3
"""Generate the browsable catalog: ``CATALOG.md`` and ``catalog.json``.

The root README is a 2,000-line landing page, the marketplace lists ~300 plugins, and
the repository holds thousands of skills. A reader's first question — *"is my journal
in here, and what do I install for it?"* — had no single place to look.

This generates that place from the same venue index the matcher uses, so the catalog
cannot drift away from what the agent actually sees:

* ``CATALOG.md``  — grouped by discipline, one row per venue, with its install target.
* ``catalog.json`` — the same data for tooling (a filter UI, an external site, scripts).

Usage:  python3 tools/gen_catalog.py [--check]
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from collections import Counter, defaultdict

from venue_lib import ROOT

INDEX = ROOT / "shared-resources/journal-selection/venue-index.tsv"
MARKETPLACE = ROOT / ".claude-plugin/marketplace.json"
OUT_MD = ROOT / "CATALOG.md"
OUT_JSON = ROOT / "catalog.json"

REPO = "https://github.com/brycewang-stanford/awesome-journal-skills"


def plugin_names() -> dict[str, str]:
    """pack_dir -> marketplace plugin name (what `/plugin install` takes)."""
    data = json.loads(MARKETPLACE.read_text(encoding="utf-8"))
    out = {}
    for plugin in data.get("plugins", []):
        source = plugin.get("source", "").lstrip("./").rstrip("/")
        if source:
            out[source] = plugin["name"]
    return out


def load() -> list[dict]:
    rows = list(csv.DictReader(INDEX.open(encoding="utf-8"), delimiter="\t"))
    names = plugin_names()
    for row in rows:
        row["plugin"] = names.get(row["pack_dir"], "")
    return rows


def render_markdown(rows: list[dict]) -> str:
    by_discipline: dict[str, list[dict]] = defaultdict(list)
    for row in rows:
        by_discipline[row["discipline"]].append(row)

    coverage = Counter(r["coverage"] for r in rows)
    types = Counter(r["venue_type"] for r in rows)
    regions = Counter(r["region"] for r in rows)

    lines = [
        "# Catalog — every venue in this repository",
        "",
        "> Generated by `python3 tools/gen_catalog.py`. Do not edit by hand.",
        "",
        f"**{len(rows)} venues** · {coverage['depth']} with a dedicated depth pack · "
        f"{coverage['breadth']} covered as a profile inside a discipline bundle · "
        f"{types['journal']} journals / {types['conference']} conferences · "
        f"{regions['international']} international / {regions['china']} China.",
        "",
        "## How to read this",
        "",
        "| Column | Meaning |",
        "|---|---|",
        "| **Coverage** | `depth` — its own pack: a full skill stack across the "
        "manuscript lifecycle plus a live-checked `official-source-map.md`. "
        "`breadth` — one venue-profile skill (fit, framing, evidence bar, house style, "
        "desk-reject triggers) inside a discipline bundle. |",
        "| **Install** | the plugin name for `/plugin install <name>`. Breadth venues "
        "share their bundle's plugin. |",
        "| **Lane** | `empirical` / `theory` / `review` / `qualitative` — do not send a "
        "qualitative or theory paper to an empirical-only venue. |",
        "| **Tier** | an *indicative bucket*, never a ranking or a bibliometric claim. |",
        "",
        "Not sure which venue you want? That is what the matcher is for:",
        "",
        "```bash",
        "/plugin install research-toolkit-skills   # then ask rt-journal-match",
        "```",
        "",
        "It profiles the paper and shortlists from this same index into "
        "reach / match / safe with a resubmission ladder. Its retrieval step is scored "
        "in [`shared-resources/journal-selection/eval/`]"
        "(shared-resources/journal-selection/eval/README.md).",
        "",
        "## Venues by discipline",
        "",
    ]

    for discipline in sorted(by_discipline):
        venues = sorted(by_discipline[discipline], key=lambda r: r["display_name"].lower())
        lines.append(f"### {discipline} ({len(venues)})")
        lines.append("")
        lines.append("| Venue | Coverage | Region | Lane | Tier | Install |")
        lines.append("|---|---|---|---|---|---|")
        for venue in venues:
            target = venue["pack_dir"] if venue["coverage"] == "depth" else venue["profile_path"]
            name = f"[{venue['display_name']}]({target})"
            plugin = f"`{venue['plugin']}`" if venue["plugin"] else "—"
            lines.append(
                f"| {name} | {venue['coverage']} | {venue['region']} | "
                f"{venue['lane']} | {venue['tier']} | {plugin} |"
            )
        lines.append("")

    lines += [
        "---",
        "",
        "Machine-readable form: [`catalog.json`](catalog.json). Regenerate both with "
        "`python3 tools/gen_catalog.py` after adding or reclassifying a pack.",
        "",
    ]
    return "\n".join(lines)


def render_json(rows: list[dict]) -> str:
    payload = {
        "repository": REPO,
        "venue_count": len(rows),
        "generated_by": "tools/gen_catalog.py",
        "notes": {
            "tier": "indicative bucket, not a ranking or bibliometric claim",
            "volatile_facts": "fees, acceptance rates, turnaround and page limits are "
                              "never in this file; read the pack's "
                              "resources/official-source-map.md",
        },
        "venues": [
            {
                "venue_id": r["venue_id"],
                "display_name": r["display_name"],
                "coverage": r["coverage"],
                "venue_type": r["venue_type"],
                "discipline": r["discipline"],
                "region": r["region"],
                "lane": r["lane"],
                "tier": r["tier"],
                "ranking_labels": [x for x in r["ranking_labels"].split(";") if x],
                "scope_keywords": [x for x in r["scope_keywords"].split(";") if x],
                "plugin": r["plugin"],
                "pack_dir": r["pack_dir"],
                "profile_path": r["profile_path"],
                "source_map": r["source_map"],
            }
            for r in rows
        ],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed catalog differs from a fresh build")
    args = parser.parse_args(argv)

    rows = load()
    markdown, payload = render_markdown(rows), render_json(rows)

    if args.check:
        stale = [
            path.relative_to(ROOT).as_posix()
            for path, text in ((OUT_MD, markdown), (OUT_JSON, payload))
            if (path.read_text(encoding="utf-8") if path.exists() else "") != text
        ]
        if stale:
            print(f"FAIL: stale catalog ({', '.join(stale)}) — run "
                  "`python3 tools/gen_catalog.py`", file=sys.stderr)
            return 1
        print(f"OK: catalog current ({len(rows)} venues)")
        return 0

    OUT_MD.write_text(markdown, encoding="utf-8")
    OUT_JSON.write_text(payload, encoding="utf-8")
    unresolved = sum(1 for r in rows if not r["plugin"])
    print(f"wrote CATALOG.md + catalog.json ({len(rows)} venues, "
          f"{len({r['discipline'] for r in rows})} disciplines)")
    if unresolved:
        print(f"  venues without a marketplace plugin entry: {unresolved}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
